AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Fortinet::FortiGate::SystemDns resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.fortinet.fortigate.systemdns.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/fortinet-fortigate-systemdns-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.fortinet.fortigate.systemdns.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/fortinet-fortigate-systemdns-handler-1.0-SNAPSHOT.jar

